---
# This playbook deploys a simple standalone JBoss server.

- hosts: jboss-servers
  remote_user: root
  sudo: yes
  roles:
    - jboss-standalone

- hosts: lbservers
  remote_user: root
  sudo: yes
  roles:
    - haproxy
