---
# This playbook deploys a simple standalone JBoss server.

- hosts: jboss-servers
  remote_user: root
  sudo: yes
  roles:
    - jboss-standalone

- hosts: lbservers
  remote_user: root
  sudo: yes
  vars:
    haproxy_template: 'haproxy.cfg.j2'
  roles:
    - haproxy

- hosts: elastic
  remote_user: root
  sudo: yes
  vars:
    haproxy_template: 'elastic_haproxy.cfg.j2'
  roles:
    - haproxy
