---
tower.localdomain:
  memory: 1024
  cpus: 1
  address: 192.168.1.50
  box: tower-2.4.3

rundeck.localdomain:
  memory: 1024
  cpus: 1
  address: 192.168.1.49
  box: geerlingguy/centos7

jboss01.localdomain:
  memory: 1024
  cpus: 1
  address: 192.168.1.51
  box: geerlingguy/centos7

jboss02.localdomain:
  memory: 1024
  cpus: 1
  address: 192.168.1.52
  box: geerlingguy/centos7

haproxy01.localdomain:
  memory: 1024
  cpus: 1
  address: 192.168.1.53
  box: geerlingguy/centos7

jboss03.localdomain:
  memory: 1024
  cpus: 1
  address: 192.168.1.54
  box: geerlingguy/centos7
